### ISSUE TITLE
tracing: build test harness to verify spans are generated with Cloud Spanner emulator

### ISSUE THREAD

**Issue by odeke-em** [odeke-em/nodejs-spanner#4]
We need a clear test harness that can be ran per test, to capture the respective spans and then verify with span names that we've got nested spans in the various call sequences

## Tasks
- [ ] Span capturing exporter that stores spans keyed by name or in a trie for each and fast search
- [ ] Exporter passed into the BatchSpanProcessor
- [ ] Ability to retrieve spans perhaps by name
- [ ] Each test should be able to rest the exporter
- [ ] Test to verify that gRPC spans are generated
